# Azure Pipeline Build Super Grate
# Dylan Bickerstaff

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildConfiguration64: 'Release_64'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/t:SuperGrate'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'
    
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/t:SuperGrate'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration64)'
    msbuildArchitecture: 'x64'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)\SuperGrate\bin\'
    ArtifactName: 'Release'
    publishLocation: 'Container'